language: node_js
node_js: '8'
cache: yarn
script:
- yarn build
- if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
  .travis/prepare-release.sh; fi
deploy:
  provider: npm
  email: kim@burgaard.us
  skip_cleanup: true
  api_key:
    secure: i0hM0NLgEk/QwkgLWGopWHLt18zmWeD2dXnZN9w98Q+TkmVuip6VDQQdt+oQ9ympWBEseO97JypEuzjUW+FrnX5qlF0hdA952PfBRIHN1gBlgZ5W/CnA9lBcrI6byQxaOva5Y33HQ3RxTH/6BNcfJlFWqoQhTeKG6uGlium6k8w1PGVfdfonlS0XC9mFtbd2OvDrLSX+2v4NJ6qfPbnthtx+BJhK0GGQkx/1kNRZc33PDKNCZBr8/ujhKmmAppvjJQTgIWTgvPobowX+ebjkKqLBEZPDPBmxgXRzCT9l47mmvPalLf1PzOkgnKfTDSWTLtXYAeZydikqaowDkUg7EW+wr9l+/MiLZVkbeNP0064+IYBAb2Ntjyqn1SPtkbTD6q5zJ1Wm+Na4P4TrQzPwFGgb9dWsGd0QbDH6Mj5L8dZa7OAttdy9aIm/U8jdH7D49e6je9rK1J62o9uBuKxz69g0N5gr+9oxkYOQt4D94fi34BUMEEFEiFkmqXLvXqqER8kWwi9Gd/A7yLEcow93JVtOLe05LO1QK7NiWFlyXyGsMnZ6EriegXpytmUCp+Nhk3S2ORki5n1N4RSsVQTb1bJXenbzBnO5Mnt+uG6y4rAkaq9Fpz//JogP1WUv3Yn++e/W4a9OqNFAHKb+B3TXTTLXUHhMsRcMoLBJaKdV8ko=
  on:
    branch: master
env:
  global:
    secure: ap3tYJrU8sqGRM3xJ0Dgja17tAfNHyw2qhcX+nw2za+ajQRPx0/1sFlAnJi1IDYtueg/x+qQgRAKyGB4A5KAZnWHx/zX53nfZ61z9OO5hlKBDUa+54FCLDpi6AtNQkBT8zn/T4pT4IItSB2piBiwLO3gT+AZP0uQOJ00ojjUwoEUgTMpT+mcYp/QUYp4qORWUj4ZEpEqMv60moAlqQgwWCVX0b3dpzZVy/MZwI7PSVyN+cg2EEKKPXfl9fXy7k5DyU/NBWV7/aJFf/pJRZQGDbpY7FfWpTjhsG+cf9S1QPUFMUVezW6rlSISSsar+/odbOA4EZTCPNXTsQMlFYECwnvWTfvqtzJlg8NBzl1OvJNIby4H1tPXZKO6/6IZkNU/x25rhx/oYe1fvFnQlZZxc7zagnSQa6ubjJJ9pdTANDNulg5fLTE68CZSK8fGxijX+6GrK6rPdlqotgi5npmCELLpORu33BcYNHcnzAXbwz+8qtcIHnCNJf4ayafYdTnbClKTu7F4OdtqvlNqKZWy1r7AYbeKZJF5WlCaUcYexAn6kSW+5q7Yy2N/kz6bGttHFyAf9AdtEb7RgF3G249WA81en76q4v6oru531sLn+SoN31TDNWo0Otmp2NIPdaiGhYJesp7bI3ZmCXRUojBNOSnnb6gyVoEBIArjtTk9fCw=
